[nixpacks]
node_version = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = ["pip3 install -r backend/requirements.txt", "pnpm install"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"
